name: Build creator project

on: 
  workflow_dispatch
#   push:
#     branches: [main]

jobs:
  buildCreatorForWindows:
    name: Build Creator for Windows
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - creator
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - name: Build game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: Earth9Builder.BuildScript.BuildCreator
      - name: Building the installer
        run: | 
          "c:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" Creator-Msi.wxs
          "c:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" -ext WixUIExtension -cultures:en-us Creator-Msi.wixobj -out Earth9-Creator.msi
        shell: cmd
      - name: Upload the installer as an artifact
        uses: actions/upload-artifact@v2
        with:
          path: "Earth9-Creator.msi"
          name: Earth9-Creator
          
#   buildPlayForWindows:
#     name: Build Play for Windows
#     runs-on: windows-2019
#     strategy:
#       fail-fast: false
#       matrix:
#         projectPath:
#           - creator
#         targetPlatform:
#           - StandaloneWindows64 # Build a Windows 64-bit standalone.
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#           lfs: true
#       - uses: actions/cache@v2
#         with:
#           path: ${{ matrix.projectPath }}/Library
#           key:
#             Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
#             hashFiles(matrix.projectPath) }}
#           restore-keys: |
#             Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
#             Library-${{ matrix.projectPath }}-
#             Library-
#       - name: Build game
#         uses: game-ci/unity-builder@v2
#         env:
#           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#         with:
#           projectPath: ${{ matrix.projectPath }}
#           targetPlatform: ${{ matrix.targetPlatform }}
#           buildMethod: Earth9Builder.BuildScript.BuildPlay
#           customParameters:  -quit -batchmode
#       - name: Building the installer
#         run: | 
#           "c:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" Play-Msi.wxs
#           "c:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" -ext WixUIExtension -cultures:en-us Play-Msi.wixobj -out Earth9.msi
#         shell: cmd
#       - name: Upload the installer as an artifact
#         uses: actions/upload-artifact@v2
#         with:
#           path: "Earth9.msi"
#           name: Earth9-Play.msi
          
          
          
          
#   builCreatorForMacOS:
#     name: Build Creator for MacOS
#     runs-on: macos-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         projectPath:
#           - creator
#         targetPlatform:
#           - StandaloneOSX 
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#           lfs: true
#       - uses: actions/cache@v2
#         with:
#           path: ${{ matrix.projectPath }}/Library
#           key:
#             Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
#             hashFiles(matrix.projectPath) }}
#           restore-keys: |
#             Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
#             Library-${{ matrix.projectPath }}-
#             Library-
#       - name: Building game 
#         uses: game-ci/unity-builder@v2
#         env:
#           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#         with:
#           projectPath: ${{ matrix.projectPath }}
#           targetPlatform: ${{ matrix.targetPlatform }}
#           buildMethod: Earth9Builder.BuildScript.BuildCreator
#           customParameters:  -quit -batchmode
#       - name: Run chmod
#         run: | 
#           chmod +x creator/build/mac/Earth9-Creator/Earth9-Creator.app/Contents/MacOS/*
#         shell: sh
#       - name: Run xattr
#         run: | 
#           xattr -cr creator/build/mac/Earth9-Creator/Earth9-Creator.app
#         shell: sh
#       - name: Building the installer
#         run: | 
#           brew install create-dmg
#           create-dmg --volname "Earth9-Creator installer" --background "installer_background.png" --window-pos 200 120 --window-size 800 450 --icon-size 100 --icon "Earth9-Creator.app" 200 190 --app-drop-link 600 185 --eula "lic.rtf" "Earth9-Creator.dmg" "creator/build/mac/Earth9-Creator/Earth9-Creator.app"
        
#       - name: Upload installer
#         uses: actions/upload-artifact@v2
#         if: ${{ github.event_name != 'pull_request' }}
#         with:
#           path: Earth9-Creator.dmg
#           name: Earth9-Creator.dmg
          
  buildPlayForMacOS:
    name: Build Play for MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - creator
        targetPlatform:
          - StandaloneOSX 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: Earth9Builder.BuildScript.BuildPlay
      - name: Run chmod
        run: | 
          chmod +x creator/build/mac/Earth9/Earth9.app/Contents/MacOS/*
        shell: sh
      - name: Run xattr
        run: | 
          xattr -cr creator/build/mac/Earth9/Earth9.app
        shell: sh
      - name: Building the installer
        run: | 
          brew install create-dmg
          create-dmg --volname "Earth9 installer" --background "installer_background.png" --window-pos 200 120 --window-size 800 450 --icon-size 100 --icon "Earth9.app" 200 190 --app-drop-link 600 185 --eula "lic.rtf" "Earth9.dmg" "creator/build/mac/Earth9/Earth9.app"
        
      - name: Upload installer
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: Earth9.dmg
          name: Earth9-Play.dmg
