name: Build creator project

on: 
  workflow_dispatch
#   push:
#     branches: [release-test]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - creator
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Building the installer
        run: | 
          dir build /S
          "c:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" Setup.wxs
          "c:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" -ext WixUIExtension -cultures:en-us Setup.wixobj -out Earth9-Creator.msi
        shell: cmd
      - name: Upload the installer as an artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: "Earth9-Creator.msi"
          name: Earth9-Creator
          
#   builForMacOS:
#     name: Build for MacOS
#     runs-on: macos-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         projectPath:
#           - creator
#         targetPlatform:
#           - StandaloneOSX # Build a Windows 64-bit standalone.
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#           lfs: true
#       - uses: actions/cache@v2
#         with:
#           path: ${{ matrix.projectPath }}/Library
#           key:
#             Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
#             hashFiles(matrix.projectPath) }}
#           restore-keys: |
#             Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
#             Library-${{ matrix.projectPath }}-
#             Library-
#       - uses: game-ci/unity-builder@v2
#         env:
#           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#         with:
#           projectPath: ${{ matrix.projectPath }}
#           targetPlatform: ${{ matrix.targetPlatform }}
#       - uses: actions/upload-artifact@v2
#         with:
#           name: Build-${{ matrix.targetPlatform }}
#           path: build/${{ matrix.targetPlatform }}

#       - name: Building the installer
#         run: | 
#           brew install create-dmg
#           create-dmg --volname "Application Installer" --background "installer_background.png" --window-pos 200 120 --window-size 800 450 --icon-size 100 --icon "StandaloneOSX.app" 200 190 --app-drop-link 600 185 --eula "lic.rtf" "StandaloneOSX.dmg" "build/StandaloneOSX/StandaloneOSX.app"
        
#       - name: Upload the installer as an artifact
#         uses: actions/upload-artifact@v2
#         if: ${{ github.event_name != 'pull_request' }}
#         with:
#           path: StandaloneOSX.dmg
#           name: StandaloneOSX
