name: Build project for all 

on: [push]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for all supported platform
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: creator/Library
          key:
            Library-creator-StandaloneOSX-${{
            hashFiles('creator/**') }}
          restore-keys: |
            Library-creator-StandaloneOSX-
            Library-creator-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: creator
          targetPlatform: StandaloneOSX
          buildMethod: Earth9Builder.BuildScript.BuildPlay
#       - uses: game-ci/unity-builder@v2
#         env:
#           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#         with:
#           projectPath: creator
#           targetPlatform: StandaloneOSX
#           buildMethod: Earth9Builder.BuildScript.BuildCreator
#           allowDirtyBuild: true
      
      
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-creator-StandaloneWindows64-${{
            hashFiles('creator/**') }}
          restore-keys: |
            Library-creator-StandaloneWindows64-
            Library-creator-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: creator
          targetPlatform: StandaloneWindows64
          buildMethod: Earth9Builder.BuildScript.BuildPlay
          allowDirtyBuild: true
#       - uses: game-ci/unity-builder@v2
#         env:
#           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#         with:
#           projectPath: creator
#           targetPlatform: StandaloneWindows64
#           buildMethod: Earth9Builder.BuildScript.BuildCreator
#           allowDirtyBuild: true
      
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: creator/build
